const perfumeCatalog = [
    new Perfume(
        "Versace Dylan Blue",
        "Versace",
        "Woody, aromatic",
        "Grapefruit, Bergamot, Aquatic Notes, Figs",
        "Pepper, Violet, Patchouli, Papyrus, Amber, Ambroxan",
        "Tonka Bean, Saffron, Musk, Incense",
        100,
        "50ml",
        "Fragrance full of character and individuality, an expression of masculine strength and charisma.",
        "Men's Perfume",
        "/assets/men/versace-dylan-blue-pour-homme-woda-toaletowa-dla-mezczyzn.webp"
    ),
    new Perfume(
        "Emporio Armani Stronger With You",
        "Emporio Armani",
        "Woody, aromatic",
        "Pepper, Cardamom, Violet, Spices",
        "Sage",
        "Cedar, Vanilla, Chestnuts",
        100,
        "Spray",
        "A male answer to a secret equation that you will fully solve only with Her by your side.",
        "Men's Perfume",
        "./assets/men/armani-emporio-stronger-with-you-woda-toaletowa-dla-mezczyzn.webp"
    ),
    new Perfume(
        "Jean Paul Gaultier Le Beau Le Parfum",
        "Jean Paul Gaultier",
        "Woody, aromatic, oriental",
        "Coconut",
        "Tonka beans",
        "Sandalwood",
        100,
        "70ml",
        "The forbidden fruit of an extremely addictive, woody amber that tempts the senses to disobey.",
        "Men's Perfume",
        "/assets/men/jean-paul-gaultier-le-beau-le-parfum-intense-woda-perfumowana-dla-mezczyzn.webp"
    ),
    new Perfume(
        "Lattafa Khamrah",
        "Lattafa",
        "Sweet, spicy",
        "Bergamot, Cinnamon, Nutmeg",
        "Lilies of the Valley, Praline, Tuberose",
        "Tonka Bean, Benzoin, Myrrh, Wood, Vanilla, Amber Wood",
        100,
        "50ml",
        "Base notes of vanilla, tonka bean, amberwood, myrrh, benzoin, and akigala wood.",
        "Men's Perfume",
        "/assets/men/lattafa-khamrah-woda-perfumowana-unisex.webp"
    ),
    new Perfume(
        "Carolina Herrera Bad Boy",
        "Carolina Herrera",
        "Oriental, spice",
        "grapefruit, white pepper",
        "vetiver, sage",
        "tonka bean, cacao",
        100,
        "50ml",
        "Deep, sweet and spicy aroma slowly comes to the fore, giving the composition a charismatic character.",
        "Men's Perfume",
        "/assets/men/carolina-herrera-bad-boy-woda-toaletowa-dla-mezczyzn.webp"
    ),
    new Perfume(
        "Boss The Scent Elixir",
        "Hugo Boss",
        "Spicy, powdery, woody",
        "Allspice, Pimento pepper",
        "Lavender",
        "Sandalwood",
        100,
        "50ml",
        "Highly concentrated, amber and leather composition exudes pure charm.",
        "Men's Perfume",
        "/assets/men/hugo-boss-boss-the-scent-elixir-woda-perfumowana-dla-mezczyzn.webp"
    ),
    new Perfume(
        "Carolina Herrera Good Girl",
        "Carolina Herrera",
        "Floral, oriental",
        "Almond",
        "Tuberose, Jasmine",
        "Cacao, Tonka Bean",
        120,
        "80ml",
        "A bold blend of dark and light elements for the modern woman.",
        "Women's Perfume",
        "/assets/women/carolina-herrera-good-girl-woda-perfumowana-dla-kobiet.webp"
    ),
    new Perfume(
        "Giorgio Armani Si Intense",
        "Giorgio Armani",
        "Floral",
        "Blackcurrant",
        "Rose, Davana",
        "Vanilla",
        120,
        "80ml",
        "Si helps women express themselves in a bold and decisive way, but not without delicacy.",
        "Women's Perfume",
        "/assets/women/armani-si-intense-woda-perfumowana-flakon-napelnialny-dla-kobiet.webp"
    ),
    new Perfume(
        "Jean Paul Gaultier La Belle Le Parfum",
        "Jean Paul Gaultier",
        "Fruity, oriental",
        "Pear",
        "Tonka beans",
        "Vanilla, wood",
        120,
        "80ml",
        "The sensuality of this perfume is defined in the first notes by warm vanilla, which is joined after a moment by delicious, green pear.",
        "Women's Perfume",
        "/assets/women/jean-paul-gaultier-la-belle-le-parfum-woda-perfumowana-dla-kobiet.webp"
    ),
    new Perfume(
        "Marc Jacobs Daisy",
        "Marc Jacobs",
        "Floral, woody",
        "Red grapefruit, wild strawberries, violet leaves",
        "Gardenia, violet, jasmine",
        "Musk, vanilla, white wood",
        120,
        "80ml",
        "It is youthful, joyful, playful and has an effortless elegance – just like the woman for whom this iconic fragrance was created.",
        "Women's Perfume",
        "/assets/women/marc-jacobs-daisy-woda-toaletowa-dla-kobiet.webp"
    ),
    new Perfume(
        "narciso rodriguez for her",
        "narciso rodriguez for her",
        "Floral, chypre",
        "Osmanthus",
        "Musk",
        "Amber, patchouli",
        120,
        "80ml",
        "Simple design, purity and discreet luxury characterize the fragrance, reminiscent of the sensual aroma of bare skin.",
        "Women's Perfume",
        "/assets/women/narciso-rodriguez-for-her-woda-toaletowa-dla-kobiet.webp"
    ),
    new Perfume(
        "Gucci Flora Gorgeous Gardenia",
        "Gucci",
        "Fruity, floral",
        "Pear blossom, mandarin, red fruits",
        "Gardenia, jasmine absolute, plumeria",
        "Patchouli, brown sugar",
        120,
        "80ml",
        "Imagine a wonderful villa surrounded by an even more wonderful garden. This is exactly the kind of fantastic place that Gucci Flora Gorgeous Gardenia Eau de Parfum for Women will take you to.",
        "Women's Perfume",
        "/assets/women/gucci-flora-gorgeous-gardenia-woda-perfumowana-dla-kobiet.webp"
    )
];